import type { Metadata } from "next";
import "@/styles/main.scss";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";



export const metadata: Metadata = {
  title: "Full-stack developer",
  description: "Generated by Francis",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body
      >
        < Navbar />
        {children}
        < Footer />
      </body>
    </html>
  );
}
